Add test for car controller
jv-feb24-team3/car-sharing-service pull request #30
Opened 2024-06-03 12:56 UTC by DmytroHadiuchko

2024-06-03 13:25 UTC, oksana-miazina requested changes

2024-06-03 13:25 UTC, oksana-miazina commented on src/test/resources/application.properties
> +jwt.expiration=30000000000000
I assume it was unintentional

2024-06-03 15:39 UTC, oksana-miazina approved these changes

2024-06-03 16:00 UTC, ReamFOX commented on src/test/java/ua/team3/carsharingservice/controller/CarControllerTest.java
> +    }
check here if you received what you are expecting in response to your request

2024-06-04 06:40 UTC, ReamFOX approved these changes

2024-06-04 06:40 UTC, ReamFOX commented on src/test/resources/data/add-cars-into-table.sql
> +    (2, 'Tesla', 'SEDAN', 11, 180.0, 0);
```suggestion
    (2, 'Tesla', 'SEDAN', 11, 180.0, 0);
    
```

2024-06-04 06:41 UTC, merged